# Generated by Django 3.0.3 on 2020-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_auto_20200301_1726"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "amenity",
                    models.CharField(
                        choices=[
                            ("TV", "TV"),
                            ("KITCHEN", "Kitchen"),
                            ("PETS", "Pets"),
                            ("BATH", "Bathroom"),
                            ("WIFI", "wifi"),
                            ("ELEVATOR", "elevator"),
                            ("KING_SIZE", "King size bed"),
                            ("QUEEN_SIZE", "Queen size bed"),
                            ("SINGLE_BED", "Singlse bed"),
                            ("GARAGE", "Parking garage"),
                            ("SOFA", "Sofa"),
                            ("INTERNET", "Internet"),
                            ("IRON", "Iron"),
                            ("MICROWAVE", "Microwave oven"),
                            ("SAFE", "Safe"),
                            ("AIRCON", "Aircondition"),
                            ("WASHING_MACHINE", "Washing machine"),
                            ("DRYER", "Dryer"),
                            ("HAIR_DRYER", "Hair dryer"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="room",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="room", to="rooms.ImageModel"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="rooms.Amenity"),
        ),
    ]
