# Generated by Django 3.0.3 on 2020-02-19 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200217_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='room', to='rooms.ImageModel'),
        ),
    ]
