# Generated by Django 3.0.3 on 2020-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rooms", "0003_auto_20200219_1315")]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="people",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        )
    ]
