# Generated by Django 3.0.3 on 2020-04-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("rooms", "0003_auto_20200316_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="amenity",
            field=models.CharField(
                choices=[
                    ("TV", "TV"),
                    ("KITCHEN", "Kitchen"),
                    ("PETS", "Pets"),
                    ("BATH", "Bathroom"),
                    ("WIFI", "wifi"),
                    ("ELEVATOR", "elevator"),
                    ("KING_SIZE", "King size bed"),
                    ("QUEEN_SIZE", "Queen size bed"),
                    ("SINGLE_BED", "Single bed"),
                    ("GARAGE", "Parking garage"),
                    ("SOFA", "Sofa"),
                    ("INTERNET", "Internet"),
                    ("IRON", "Iron"),
                    ("MICROWAVE", "Microwave oven"),
                    ("SAFE", "Safe"),
                    ("AIRCON", "Aircondition"),
                    ("WASHING_MACHINE", "Washing machine"),
                    ("DRYER", "Dryer"),
                    ("HAIR_DRYER", "Hair dryer"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="users.Customer",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="rooms.Room",
            ),
        ),
    ]
